start_grab:
# Zero the fingers, hopefully releasing grasp
# Pull the wrist up and off the object or to clear table when starting from 0
- wait: 0
  positions: {ffj0: 0, ffj3: 0, ffj4: 0, lfj0: 0, lfj3: 0, lfj4: 0, lfj5: 0, mfj0: 0, mfj3: 0, mfj4: 0, rfj0: 0, rfj3: 0, rfj4: 0, thj1: 0, thj2: 0, thj3: 0, thj4: 0, thj5: 0, wrj1: -45, wrj2: 0}
- wait: 1 
  positions: {er: 45, es: 75}
- wait: 3 
  positions: {sr: 16, ss: 15}
- wait: 3 
  positions: {er: 45, es: 75, sr: 16, ss: 15, wrj1: -18, wrj2: -6}
zero:
- wait: 0 
  positions: {er: 0, es: 0, sr: 0, ss: 0, ffj0: 0, ffj3: 0, ffj4: 0, lfj0: 0, lfj3: 0, lfj4: 0, lfj5: 0, mfj0: 0, mfj3: 0, mfj4: 0, rfj0: 0, rfj3: 0, rfj4: 0, thj1: 0, thj2: 0, thj3: 0, thj4: 0, thj5: 0}
