collision_clearance: 0.10

collision_links:
      ffknuckle
      ffproximal
      ffmiddle
      ffdistal
      mfknuckle
      mfproximal
      mfmiddle
      mfdistal
      rfknuckle
      rfproximal
      rfmiddle
      rfdistal
      lfmetacarpal
      lfknuckle
      lfproximal
      lfmiddle
      lfdistal
      thbase
      thproximal
      thhub
      thmiddle
      thdistal

joints_costs:
      ShoulderJRotate: 1.0
      ShoulderJSwing: 1.0
      ElbowJSwing: 1.0
      ElbowJRotate: 1.0
      arm_link: 1.0
      WRJ2: 1.0
      WRJ1: 1.0

joint_velocity_limits:
      ShoulderJRotate: 1.0
      ShoulderJSwing: 1.0
      ElbowJSwing: 1.0
      ElbowJRotate: 1.0
      arm_link: 1.0
      WRJ2: 1.0
      WRJ1: 1.0

reference_frame: /base_link

collision_space:
  size_x: 3.0
  size_y: 4.0
  size_z: 2.2
  origin_x: -1.0
  origin_y: -2.0
  origin_z: -0.3
  resolution: 0.02
  field_bias_x: 0.0
  field_bias_y: 0.0
  field_bias_z: 0.0

chomp_collision_operations:
  - object1: r_end_effector
    object2: right_arm
    operation: disable

