#2 sets of thresholds used in the compliant close action:
# - the first set is used when closing the hand around the object
#   it should be a small value: the fingers will stop when they're
#   touching the object with this given force when first closing.
# - the second set should be bigger: it's the force with which the
#   fingers will close around the object to lift it.

light_touch_thresholds:
 - 1.0
 - 0.0
 - 0.0
 - 0.0
 - 1.0
grasp_touch_thresholds:
 - 1.2
 - 0.0
 - 0.0
 - 0.0
 - 1.2
