joint_limits:
  ShoulderJRotate:
    has_position_limits: true
    min_position: -1.57079632679
    max_position: 0.785398163397
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 1.0
    angle_wraparound: false
  ShoulderJSwing:
    has_position_limits: true
    min_position: 0.0
    max_position: 1.57079632679
    has_velocity_limits: true
    max_velocity: 1.52
    has_acceleration_limits: true
    max_acceleration: 1.0
    angle_wraparound: false
  ElbowJSwing:
    has_position_limits: true
    min_position: 0.0
    max_position: 2.09439510239
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 1.0
    angle_wraparound: false
  ElbowJRotate:
    has_position_limits: true
    min_position: -1.57079632679
    max_position: 1.57079632679
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 1.0
    angle_wraparound: false
