## This file should be loaded under <robot description>_planning

## the definition of each group
groups:

  - name: right_arm
    joints:
      ShoulderJRotate
      ShoulderJSwing
      ElbowJSwing
      ElbowJRotate
      arm_link
      WRJ2
      WRJ1
    links:
      shadowarm_base
      shadowarm_trunk
      shadowarm_upperarm
      shadowarm_lowerarm
      shadowarm_handsupport_motor
      forearm_motor
      wrist
      palm
  - name: arms
    joints:
      ShoulderJRotate
      ShoulderJSwing
      ElbowJSwing
      ElbowJRotate
      arm_link
      WRJ2
      WRJ1
    links:
      shadowarm_base
      shadowarm_trunk
      shadowarm_upperarm
      shadowarm_lowerarm
      shadowarm_handsupport_motor
      forearm_motor
      wrist
      palm
    planner_configs:
      RRTkConfig2 SBLkConfig2

  - name: r_end_effector
    links:
      ffknuckle
      ffproximal
      ffmiddle
      ffdistal
      mfknuckle
      mfproximal
      mfmiddle
      mfdistal
      rfknuckle
      rfproximal
      rfmiddle
      rfdistal
      lfmetacarpal
      lfknuckle
      lfproximal
      lfmiddle
      lfdistal
      thbase
      thproximal
      thhub
      thmiddle
      thdistal

