# Define the goal
#No goal msg will be defined for this action (sending an empty goal will trigger the recognition process)
---
# Define the result
handle_demo_step_actions/TableObject[] objects
string collision_support_surface_name
---
# Define a feedback message
uint32 percent_complete

string feedback_information_message
