# Define the goal
geometry_msgs/PoseStamped place_pose
handle_demo_step_actions/TableObject object_to_place
object_manipulation_msgs/Grasp executed_grasp
string collision_support_surface_name
---
# Define the result
uint32 result
---
# Define a feedback message
uint32 percent_complete

string feedback_information_message
